language: node_js
node_js:
  - "5.6"
before_script:
  - npm install -g knex
  - export NODE_ENV=test
  - createdb RNTR_test
  - node db/dbConfig.js
  - npm test 
addons: 
  postgresql: "9.3"
services:
  - postgresql